### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by amyquispe** [lighterletter/HW_03-20#1]
Divisor Pattern

Interesting choice to wrap System.out.println - would have loved a comment as to why. Overall very clean and organized.

Twenty Questions

Q>=1 is the same as Q>0. I'm more used to seeing the second, although your code is readable as is. Another option would be to count up, in which case I might expect to see for(Q=0;Q<20;Q++) or (Q=1;Q<=20;Q++).

Very good - love how short your code is! One suggestion is if the user never guesses the number, it might be nice to tell them what the number was.

Fibonacci

Might suggest a naming scheme such as fib1 & fib2. i & j tend to be for iterating esp in a 2d form. next & prev might also work, although that tends to be better for a pointers/linked list situation.

Missed then n = 0 case.

Missing curly braces around else case. Poor indentation.

A Pretty Title

Does not take into account special cases (like 'a', 'an', 'or').

Very clean code otherwise. Love the way it's organized and the utilization of the libraries. Very readable.

Verbosity

Closing curly braces should generally be on a separate line from new code.

Instead of repeating code for each case, break it out into a function that takes in the File name and then call it on each file.

Account for more cases such as Mrs. and Mr., which have periods but don't end sentences and ! and ?, which end sentences instead of periods.

**Comment by lighterletter** [comment]
I'm sure I must've said it in person, but I'll write it here as well. Thanks for the feedback Amy!
